"""Added has_agreed field to participant model

Revision ID: 41935b3fcf8d
Revises: fcdea16ad87c
Create Date: 2023-09-16 17:41:34.908515

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41935b3fcf8d'
down_revision = 'fcdea16ad87c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'date_sent')
    op.drop_column('chats', 'text')
    op.add_column('participants', sa.Column('has_agreed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'has_agreed')
    op.add_column('chats', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('date_sent', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
