"""Created Meeting Chat Message Participant models, updated User model

Revision ID: 518070929cd1
Revises: 8f02d4ba1734
Create Date: 2023-08-19 06:15:27.347047

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geography


# revision identifiers, used by Alembic.
revision = '518070929cd1'
down_revision = '8f02d4ba1734'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_place', geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('meeting_initialization_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_meetings_meeting_place', 'meetings', ['meeting_place'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('date_sent', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('route', geoalchemy2.types.Geography(geometry_type='LINESTRING', from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_participants_route', 'participants', ['route'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('date_sent', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.add_column('users', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'), nullable=True))
    op.add_column('users', sa.Column('location_update_date', sa.DateTime(), nullable=True))
    # op.create_index('idx_users_location', 'users', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_users_location', table_name='users', postgresql_using='gist')
    op.drop_column('users', 'location_update_date')
    op.drop_column('users', 'location')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    # op.drop_index('idx_participants_route', table_name='participants', postgresql_using='gist')
    op.drop_table('participants')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    # op.drop_index('idx_meetings_meeting_place', table_name='meetings', postgresql_using='gist')
    op.drop_table('meetings')
    # ### end Alembic commands ###
