"""upgraded to mapped columns

Revision ID: 7bda3aef0c35
Revises: 518070929cd1
Create Date: 2023-08-19 11:36:51.863212

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '7bda3aef0c35'
down_revision = '518070929cd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('participants', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('participants', 'meeting_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('participants', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
