"""fixed imports

Revision ID: 8f2ad97a882e
Revises: 7bda3aef0c35
Create Date: 2023-08-19 12:09:46.439818

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '8f2ad97a882e'
down_revision = '7bda3aef0c35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
