"""changed env py

Revision ID: 98b59eea8d3c
Revises: a4bdea38491f
Create Date: 2023-08-19 14:24:59.397661

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '98b59eea8d3c'
down_revision = 'a4bdea38491f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
