"""placed participant model import inside user

Revision ID: e9642249ebec
Revises: 98b59eea8d3c
Create Date: 2023-08-19 14:26:31.739626

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e9642249ebec'
down_revision = '98b59eea8d3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
