"""placed chat model import inside meeting

Revision ID: fcdea16ad87c
Revises: e9642249ebec
Create Date: 2023-08-19 14:28:08.045811

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'fcdea16ad87c'
down_revision = 'e9642249ebec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
